// src/components/top/Top.vue
<template>
  <v-container fill-height>
    <v-layout align-center justify-center>
      <v-card width="420" color="rgba(255, 255, 255, 0.9)" class="elevation-6">
        <v-container class="pa-6" align-center justify-center>
          <h2 class="text-xs-center">Ark</h2>
          <p class="text-xs-center mb-2">
            I <v-icon small>favorite</v-icon> creating something!
          </p>
          <v-divider></v-divider>
          <v-layout class="ma-2 pa-0">
            <ark-icon></ark-icon>
          </v-layout>
          <p class="text-xs-center mb-1">
            Mathematics / Computer Science / Programming
          </p>
          <v-layout align-center justify-center>
            <v-btn
              v-for="(account, key) in accountList"
              :key="key"
              icon
              medium
              flat
              class="mx-1 my-0"
              :href="account.url"
            >
              <v-icon size="28px">{{ account.iconName }}</v-icon>
            </v-btn>
          </v-layout>
        </v-container>
      </v-card>
    </v-layout>
  </v-container>
</template>

<script>
import ArkIcon from "@/components/top/ArkIcon.vue";

export default {
  data: function() {
    return {
      accountList: [
        {
          url: "https://github.com/ArkArk",
          iconName: "fab fa-github"
        },
        {
          url: "https://twitter.com/arkark_",
          iconName: "fab fa-twitter"
        },
        {
          url: "http://ark4rk.hatenablog.com/",
          iconName: "fas fa-rss"
        }
      ]
    };
  },
  components: {
    ArkIcon
  }
};
</script>

// src/components/top/Top.tsx
import {
  Box,
  Divider,
  Flex,
  HStack,
  Heading,
  Icon,
  Spacer,
  Text,
} from "@chakra-ui/react";
import { FaGithub, FaHeart, FaPenNib, FaTwitter } from "react-icons/fa";

import CornerButtons from "./CornerButtons";

import BioIcon from "@/components/top/BioIcon";
import Link from "@/components/utils/Link";

const Top: React.FC = () => {
  const bioIconSize = 128;
  const linkIconSize = 8;

  return (
    <Box color="white">
      <BioIcon
        w="100vw"
        h="100vh"
        contentW={bioIconSize}
        contentH={bioIconSize}
        position="absolute"
      ></BioIcon>
      <CornerButtons></CornerButtons>
      <Flex
        w="100vw"
        h="50vh"
        direction="column"
        align="center"
        top={0}
        left={0}
      >
        <Spacer></Spacer>
        <Heading size="lg" mb={0}>
          {"Ark's page"}
        </Heading>
        <Text mb={1}>
          I <Icon as={FaHeart} boxSize={3} mx={0.5}></Icon> creating something!
        </Text>
        <Divider w={420} mb={4}></Divider>
        <Box h={`${(bioIconSize / 2) | 0}px`}></Box>
      </Flex>
      <Flex
        w="100vw"
        h="50vh"
        direction="column"
        align="center"
        top={0}
        left={0}
      >
        <Box h={`${(bioIconSize / 2) | 0}px`}></Box>
        <Text fontSize="sm" fontWeight="bold" mb={3}>
          Mathematics / Computer Science / Programming
        </Text>
        <HStack wrap="wrap" spacing={5}>
          <Link href="https://github.com/arkark" isExternal>
            <Icon as={FaGithub} boxSize={linkIconSize}></Icon>
          </Link>
          <Link href="https://twitter.com/arkark_" isExternal>
            <Icon as={FaTwitter} boxSize={linkIconSize}></Icon>
          </Link>
          <Link href="https://blog.arkark.dev/" isExternal>
            <Icon as={FaPenNib} boxSize={linkIconSize}></Icon>
          </Link>
        </HStack>
        <Spacer></Spacer>
      </Flex>
    </Box>
  );
};

export default Top;
