// src/components/about/AboutInterest.tsx
import { List } from "@chakra-ui/react";

import H3 from "@/components/utils/H3";
import ListItemWithIcon from "@/components/utils/ListItemWithIcon";

const AboutInterest: React.VFC = () => {
  return (
    <>
      <H3>Interests</H3>
      <List>
        <ListItemWithIcon>Algorithms / Data Structures</ListItemWithIcon>
        <ListItemWithIcon>Distributed Systems</ListItemWithIcon>
        <ListItemWithIcon>Web Security / Web Exploitation</ListItemWithIcon>
        <ListItemWithIcon>Creative Coding / Generative Design</ListItemWithIcon>
        <ListItemWithIcon>Algebra for Computer Science</ListItemWithIcon>
      </List>
    </>
  );
};

export default AboutInterest;

// src/components/about/card/AboutInterest.vue
<template>
  <about-card :title="'興味分野'">
    <ul class="fa-ul ma-0">
      <li v-for="(item, index) in items" :key="index" class="mb-1">
        <span class="fa-li"><i class="fas fa-hashtag"></i></span>
        <span>{{ item }}</span>
      </li>
    </ul>
  </about-card>
</template>

<script>
import AboutCard from "@/components/about/card/AboutCard";

export default {
  data: function () {
    return {
      items: [
        "Algorithms and Data Structures",
        "Distributed Systems",
        "Cyber Security",
        "Generative Design",
      ],
    };
  },
  components: {
    AboutCard,
  },
};
</script>
