// src/components/about/AboutActivity.tsx
import { HStack, List, chakra } from "@chakra-ui/react";

import H3 from "@/components/utils/H3";
import Link from "@/components/utils/Link";
import ListItemWithIcon from "@/components/utils/ListItemWithIcon";

const AboutActivity: React.FC = () => {
  return (
    <>
      <H3>Activities</H3>
      <List>
        <ListItemWithIcon>
          <HStack wrap="wrap" spacing={1}>
            <chakra.span>SECCON CTF 2023 Finals</chakra.span>
          </HStack>
        </ListItemWithIcon>
        <ListItemWithIcon>
          <Link
            href="https://github.com/arkark/my-ctf-challenges#seccon-ctf-2023-quals"
            isExternal
          >
            SECCON CTF 2023 Quals
          </Link>
        </ListItemWithIcon>
        <ListItemWithIcon>
          <Link
            href="https://github.com/arkark/my-ctf-challenges#seccon-ctf-2022-finals"
            isExternal
          >
            SECCON CTF 2022 Finals
          </Link>
        </ListItemWithIcon>
        <ListItemWithIcon>
          <Link
            href="https://github.com/arkark/my-ctf-challenges#seccon-ctf-2022-quals"
            isExternal
          >
            SECCON CTF 2022 Quals
          </Link>
        </ListItemWithIcon>
        <ListItemWithIcon>
          <Link
            href="https://github.com/arkark/my-ctf-challenges#seccon-ctf-2021"
            isExternal
          >
            SECCON CTF 2021
          </Link>
        </ListItemWithIcon>
        <ListItemWithIcon>
          <Link href="https://atcoder.jp/contests/ttpc2019" isExternal>
            東京工業大学プログラミングコンテスト2019
          </Link>
        </ListItemWithIcon>
        <ListItemWithIcon>
          第4回ゲーム制作者交流イベント
          <Link href="https://game3.trap.jp/" isExternal>
            GAME<chakra.sup>3</chakra.sup>
          </Link>
        </ListItemWithIcon>
        <ListItemWithIcon>
          第3回ゲーム制作者交流イベント
          <Link href="https://game3.trap.jp/" isExternal>
            GAME<chakra.sup>3</chakra.sup>
          </Link>
        </ListItemWithIcon>
      </List>
    </>
  );
};

export default AboutActivity;

// src/components/about/card/AboutActivity.vue
<template>
  <about-card :title="'活動'">
    <p class="mb-1">
      <span>TTPC</span>
    </p>
    <ul class="fa-ul ma-0">
      <li class="ml-1 mb-1">
        <span class="fa-li"><i class="fas fa-hashtag"></i></span>
        <span>東京工業大学プログラミングコンテスト2019 : 運営</span>
        <span>
          <link-icon :url="'https://atcoder.jp/contests/ttpc2019'"></link-icon>
        </span>
      </li>
    </ul>
    <p class="mb-1">
      <span>GAME<sup>3</sup></span>
      <span>
        <link-icon :url="'https://game3.trap.jp'"></link-icon>
      </span>
    </p>
    <ul class="fa-ul ma-0">
      <li class="ml-1 mb-1">
        <span class="fa-li"><i class="fas fa-hashtag"></i></span>
        <span>第4回ゲーム製作者交流会GAME<sup>3</sup> : 運営</span>
      </li>
      <li class="ml-1 mb-1">
        <span class="fa-li"><i class="fas fa-hashtag"></i></span>
        <span>第3回ゲーム製作者交流会GAME<sup>3</sup> : 運営</span>
      </li>
    </ul>
  </about-card>
</template>

<script>
import AboutCard from "@/components/about/card/AboutCard";
import LinkIcon from "@/components/about/icon/LinkIcon";

export default {
  components: {
    AboutCard,
    LinkIcon,
  },
};
</script>
